import type { Metadata } from "next";
import {Inter, Martian_Mono} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import React from "react";

const inter = Inter(
    { subsets: ["latin"],
      variable: "--font-inter"
    }
);

const martianMono = Martian_Mono(
    { subsets: ["latin"],
        variable: "--font-martian"
    }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"dark"}>
      <body className={cn(
          "min-h-screen font-inter antialiased",
          inter.className
      )}>{children}</body>
    </html>
  );
}
