import type { Metadata } from "next";
import { Inter, Martian_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/toaster";
import { ExternalLink } from "lucide-react";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

const martianMono = Martian_Mono({
	subsets: ["latin"],
	variable: "--font-martian",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"dark relative w-screen min-h-dvh font-inter antialiased overflow-x-hidden",
					inter.className,
				)}
			>
				<header className="absolute top-0 left-1/2 -translate-x-[50%] z-50 w-full max-w-6xl flex justify-end py-6">
					<nav>
						<ul>
							<li>
								<Button
									variant={"link"}
									className="group no-underline!"
								>
									<Link
										href={"/resume.pdf"}
										rel="noreferer"
										target={"_blank"}
										className="border-b border-transparent group-hover:border-primary"
									>
										<span>Resume </span>
										<ExternalLink className="inline-block size-4 -mt-1" />
									</Link>
								</Button>
							</li>
						</ul>
					</nav>
				</header>
				{children}

				<Toaster />
			</body>
		</html>
	);
}
