name: Build Nextjs app

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [master]
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build Project
        run: npm run build